/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellerOrdersRouteImport } from './routes/seller-orders'
import { Route as SellerBooksRouteImport } from './routes/seller-books'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as OrderRouteImport } from './routes/order'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AddBookRouteImport } from './routes/add-book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditBookBookIdRouteImport } from './routes/edit-book.$bookId'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'

const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/seller-orders',
  path: '/seller-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerBooksRoute = SellerBooksRouteImport.update({
  id: '/seller-books',
  path: '/seller-books',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBookRoute = AddBookRouteImport.update({
  id: '/add-book',
  path: '/add-book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditBookBookIdRoute = EditBookBookIdRouteImport.update({
  id: '/edit-book/$bookId',
  path: '/edit-book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-book': typeof AddBookRoute
  '/books': typeof BooksRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/order-success': typeof OrderSuccessRoute
  '/register': typeof RegisterRoute
  '/seller-books': typeof SellerBooksRoute
  '/seller-orders': typeof SellerOrdersRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/edit-book/$bookId': typeof EditBookBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-book': typeof AddBookRoute
  '/books': typeof BooksRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/order-success': typeof OrderSuccessRoute
  '/register': typeof RegisterRoute
  '/seller-books': typeof SellerBooksRoute
  '/seller-orders': typeof SellerOrdersRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/edit-book/$bookId': typeof EditBookBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-book': typeof AddBookRoute
  '/books': typeof BooksRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/order-success': typeof OrderSuccessRoute
  '/register': typeof RegisterRoute
  '/seller-books': typeof SellerBooksRoute
  '/seller-orders': typeof SellerOrdersRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/edit-book/$bookId': typeof EditBookBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-book'
    | '/books'
    | '/cart'
    | '/login'
    | '/order'
    | '/order-success'
    | '/register'
    | '/seller-books'
    | '/seller-orders'
    | '/book/$bookId'
    | '/edit-book/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-book'
    | '/books'
    | '/cart'
    | '/login'
    | '/order'
    | '/order-success'
    | '/register'
    | '/seller-books'
    | '/seller-orders'
    | '/book/$bookId'
    | '/edit-book/$bookId'
  id:
    | '__root__'
    | '/'
    | '/add-book'
    | '/books'
    | '/cart'
    | '/login'
    | '/order'
    | '/order-success'
    | '/register'
    | '/seller-books'
    | '/seller-orders'
    | '/book/$bookId'
    | '/edit-book/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddBookRoute: typeof AddBookRoute
  BooksRoute: typeof BooksRoute
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  OrderRoute: typeof OrderRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  RegisterRoute: typeof RegisterRoute
  SellerBooksRoute: typeof SellerBooksRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  BookBookIdRoute: typeof BookBookIdRoute
  EditBookBookIdRoute: typeof EditBookBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seller-orders': {
      id: '/seller-orders'
      path: '/seller-orders'
      fullPath: '/seller-orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-books': {
      id: '/seller-books'
      path: '/seller-books'
      fullPath: '/seller-books'
      preLoaderRoute: typeof SellerBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-book': {
      id: '/add-book'
      path: '/add-book'
      fullPath: '/add-book'
      preLoaderRoute: typeof AddBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-book/$bookId': {
      id: '/edit-book/$bookId'
      path: '/edit-book/$bookId'
      fullPath: '/edit-book/$bookId'
      preLoaderRoute: typeof EditBookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddBookRoute: AddBookRoute,
  BooksRoute: BooksRoute,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  OrderRoute: OrderRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  RegisterRoute: RegisterRoute,
  SellerBooksRoute: SellerBooksRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  BookBookIdRoute: BookBookIdRoute,
  EditBookBookIdRoute: EditBookBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
